### ISSUE TITLE
Error: org/apache/log4j/PropertyConfigurator

### ISSUE THREAD

**Issue by drarpitgaur24** [Rothamsted/knetbuilder#51] opened 2021-09-28 06:55 UTC
I do have a java version 17 on my Windows 10 workstation which has all minimum configuration requirements to install ondex GUI. But I am receiving the above-mentioned error, even after trying different system compatibilities.  
How can I encounter it?

**Comment by marco-brandizi** [comment] 2021-09-29 10:58
Java 17 has just been released and we will need some time to test our software with it and possibly make the necessary compatibility upgrades. Until then, I'd recommend to use the 11 (we tend to use the Java LTS versions only, since it's very hard to keep up with their new release policy).

Regarding the specific error, please could you give us more details? The best way to do that under Windows is running ondex.ps1 from a Powershell window and using the '>' [redirection operator][10] and send us (ie, attach hereby) the resulting output file.

[10]: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection?view=powershell-7.1

**Comment by drarpitgaur24** [comment] 2021-09-29 11:48
Thank you for this prompt response. I tried it with JDK 11, but the problem persisted (See attachment). The ondex.ps1 didn't run, anyhow.

<img width="693" alt="Error" src="https://user-images.githubusercontent.com/79159594/135262301-b9090c42-1b24-45ef-a5c2-0d19186e7f49.PNG">

**Comment by marco-brandizi** [comment] 2022-01-10 15:22
Closing it with non-reproducible tag. Please, possibly reopen with details.

**Closed by marco-brandizi** 2022-01-10 15:22 UTC
